server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://brandi-story.c1oigou8k06a.ap-northeast-2.rds.amazonaws.com:3306/brandi_story?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: brandi123

jwt:
  source:
    access-secret-key: "SECRET_KEY"
    refresh-secret-key: "REFRESH_SECRET_KEY"

  valid-time:
    access-token: 3600000  # 1시간 (60 * 60 * 1000L)
    refresh-token: 86400000 # 1일 (24 * 60 * 60 * 1000L)

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/brandi_story?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 8282

#datasource:
#  username: ${DATABASE_USERNAME}
#  password: ${DATABASE_PASSWORD}
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/chapter_96?useUnicode=true&characterEncoding=UTF-8
#
#datasource2:
#  username: ${DATABASE_USERNAME}
#  password: ${DATABASE_PASSWORD}
#  url: jdbc:mysql://localhost:3306/chapter_97?useUnicode=true&characterEncoding=UTF-8
#  driver-class-name: com.mysql.cj.jdbc.Driver
#
#jwt:
#  secret-key-source: ${JWT_SECRET_KEY}

