spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8085

logging:
  config: classpath:logback-spring-dev.xml
  level:
    org:
      hibernate:
        SQL: DEBUG

datasource:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://brandi-story.c1oigou8k06a.ap-northeast-2.rds.amazonaws.com:3306/brandi_story?useUnicode=true&characterEncoding=UTF-8

jwt:
  source:
    access-secret-key: ${JWT_ACCESS_SECRET_KEY}
    refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}

  valid-time:
    access-token: 3600000  # 1시간 (60 * 60 * 1000L)
    refresh-token: 86400000 # 1일 (24 * 60 * 60 * 1000L)
